name: Generate CHANGELOG.md on release branch

on:
  push:
    tags:
        - 'v*'

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Get the version
          id: get_version
          run: |
            tail -n +4 CHANGELOG.md | sed -e '/##/,$d' > RELEASE_CHANGELOG.txt
            echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        - name: Create Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            name: Release of ${{ steps.get_version.outputs.VERSION }}
            body_path: RELEASE_CHANGELOG.txt
            files: CHANGELOG.md
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
